name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Restore Infra.Azure
      run: dotnet restore ./*/Infra.Azure.slnx

    - name: Build Infra.Azure
      run: dotnet build ./*/Infra.Azure.slnx --no-restore -c Release

    - name: Test Infra.Azure
      run: dotnet test ./*/Infra.Azure.slnx --no-restore -c Release

    - name: Pack Infra.Azure
      run: dotnet pack ./*/Infra.Azure.slnx --no-build -o ~/nuget -c Release

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push ~/nuget/*.nupkg
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NUGET_SECRET }}
        --skip-duplicate